global:
  enabled: true
  tlsDisable: false
injector:
  enabled: false
server:
%s
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault-ca-crt/tls.crt
  extraVolumes:
    - type: secret
      name: tls-server
    - type: secret
      name: vault-ca-crt
  auditStorage:
    enabled: true
    size:  %s
  standalone:
    enabled: false
  service:
    annotations: 
      external-dns.alpha.kubernetes.io/hostname: %s
    type: "LoadBalancer"
  dataStorage:
    size: %s
%s
ui:
  enabled: %t
  annotations: 
    external-dns.alpha.kubernetes.io/hostname: %s
  serviceType: "LoadBalancer"
  serviceNodePort: null
  externalPort: %d
  # loadBalancerIP: "192.168.20.238/32"
